import { useEffect, useMemo, useState } from 'react';
import { Card, DatePicker, Empty, Segmented, Select, Statistic, Table, Tag } from 'antd';
import dayjs from 'dayjs';
import { ALL_MEMBERS, ALL_TEAMS, Team } from '@/constants';
import { Task, TaskContribution } from '@/types';
import { getAllTaskContributions } from '@/services/settlementService';
import { getTasks } from '@/services/taskService';
import { useActor } from '@/contexts/ActorContext';

export default function PersonalWork() {
  const [tasks, setTasks] = useState<Task[]>([]); const [items, setItems] = useState<TaskContribution[]>([]); const [member, setMember] = useState<string>(); const [team, setTeam] = useState<Team>(); const [periodMode, setPeriodMode] = useState<'日' | '周' | '月'>('周'); const [anchorDate, setAnchorDate] = useState(dayjs());
  const { actor } = useActor();
  useEffect(() => { getTasks().then(setTasks); getAllTaskContributions().then(setItems); }, []);
  const start = periodMode === '日' ? anchorDate.startOf('day') : periodMode === '周' ? anchorDate.startOf('week') : anchorDate.startOf('month');
  const end = periodMode === '日' ? anchorDate.endOf('day') : periodMode === '周' ? anchorDate.endOf('week') : anchorDate.endOf('month');
  const periodLabel = periodMode === '日' ? '当日' : periodMode === '周' ? '本周' : '本月';
  const rows = useMemo(() => items.filter(item => item.status === 'confirmed').filter(item => actor.role !== '组员' || item.member === actor.name).filter(item => (!member || item.member === member)).filter(item => { const task = tasks.find(row => row.id === item.taskId); const permittedTeam = actor.role === '管理员' || task?.team === actor.team; return permittedTeam && (!team || task?.team === team); }).filter(item => dayjs(item.confirmedAt || item.attachedAt).isAfter(start.subtract(1, 'day')) && dayjs(item.confirmedAt || item.attachedAt).isBefore(end.add(1, 'day'))).map(item => ({ ...item, task: tasks.find(task => task.id === item.taskId) })), [items, member, team, tasks, actor, start.valueOf(), end.valueOf()]);
  const tagCounts = useMemo(() => rows.reduce((result, item) => ({ ...result, [item.tag]: (result[item.tag] || 0) + 1 }), {} as Record<string, number>), [rows]);
  const isMember = actor.role === '组员'; const isLeader = actor.role === '组长';
  const pageTitle = isMember ? '我的工作记录' : isLeader ? '本组工作记录' : '人员作业明细';
  return <div><div className="page-title-row"><div><span className="eyebrow">PERSONAL OUTPUT</span><h2>{pageTitle}</h2><p>仅统计已由组长确认的工作标签和已验收关联依据，可按日、周、月复盘已确认工作量。</p></div></div><Card className="personal-filter-card"><div className="timeline-filter-row">{!isMember && <Select allowClear placeholder="筛选小组" style={{ width: 160 }} value={team} onChange={setTeam} options={(isLeader ? [actor.team] : ALL_TEAMS).filter(Boolean).map(value => ({ value, label: value }))} />}{!isMember && <Select allowClear showSearch optionFilterProp="label" placeholder="筛选成员" style={{ width: 160 }} value={member} onChange={setMember} options={ALL_MEMBERS.map(value => ({ value, label: value }))} />}<Segmented value={periodMode} onChange={value => setPeriodMode(value as '日' | '周' | '月')} options={['日', '周', '月']} /><DatePicker picker={periodMode === '日' ? 'date' : periodMode === '周' ? 'week' : 'month'} value={anchorDate} onChange={value => value && setAnchorDate(value)} /></div></Card><div className="personal-summary"><Card><Statistic title={`${periodLabel}已确认工作项`} value={rows.length} suffix="项" /></Card><Card><Statistic title="涉及任务" value={new Set(rows.map(item => item.taskId)).size} suffix="个" /></Card><Card><Statistic title={isMember ? '我的已确认记录' : '已确认成员'} value={isMember ? rows.length : new Set(rows.map(item => item.member)).size} suffix={isMember ? '条' : '人'} /></Card></div><Card title={`${periodLabel}工作类型分布`} style={{ marginTop: 20 }}><div className="work-tag-summary">{Object.keys(tagCounts).length ? Object.entries(tagCounts).sort((a, b) => b[1] - a[1]).map(([tag, count]) => <Tag key={tag} color="purple">{tag} {count} 项</Tag>) : <span className="empty-task-state">暂无可统计的已确认工作项</span>}</div></Card><Card title={`${start.format('YYYY-MM-DD')} 至 ${end.format('YYYY-MM-DD')} · 已确认明细`} style={{ marginTop: 20 }}><Table size="small" rowKey="id" dataSource={rows} locale={{ emptyText: <Empty description="该时间范围暂无已确认工作记录" /> }} pagination={false} scroll={{ x: 950 }} columns={[{ title: '成员', dataIndex: 'member', width: 100 }, { title: '关联任务', width: 240, render: (item: any) => item.task?.name || item.taskId }, { title: '小组', width: 130, render: (item: any) => item.task?.team || '-' }, { title: '工作内容', dataIndex: 'tag', render: (value: string) => <Tag color="blue">{value}</Tag> }, { title: '确认人/时间', width: 180, render: (item: TaskContribution) => `${item.confirmedBy || '-'} · ${item.confirmedAt || '-'}` }, { title: '备注', dataIndex: 'note', width: 180 }]} /></Card></div>;
}
