import { useEffect, useState } from 'react';
import { Button, Card, Form, Input, Modal, Select, Space, Switch, Table, Tag, message } from 'antd';
import { EditOutlined, PlusOutlined, UsergroupAddOutlined } from '@ant-design/icons';
import { ALL_TEAMS, Team } from '@/constants';
import { getManagedMembers, ManagedMember, saveManagedMember, toggleManagedMember } from '@/services/memberService';
import { isGlobalManagerRole, useActor } from '@/contexts/ActorContext';

export default function MemberManagement() {
  const [members, setMembers] = useState<ManagedMember[]>([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<ManagedMember | null>(null); const [form] = Form.useForm();
  const { actor } = useActor(); const canManage = actor.role !== '组员'; const canManageMember = (item: ManagedMember) => isGlobalManagerRole(actor.role) || item.team === actor.team;
  const load = () => getManagedMembers().then(setMembers); useEffect(() => { load(); }, []);
  const edit = (item?: ManagedMember) => { setEditing(item || null); form.setFieldsValue(item || { role: '组员', status: '在职' }); setOpen(true); };
  const submit = async () => { try { const values = await form.validateFields(); await saveManagedMember({ ...values, team: actor.role === '组长' ? actor.team : values.team, id: editing?.id }); message.success(editing ? '成员信息已更新' : '成员已添加'); setOpen(false); load(); } catch {} };
  return <div><div className="page-title-row"><div><span className="eyebrow">TEAM MEMBERS</span><h2>成员管理</h2><p>组长可维护本组成员；成员调组或停用后，历史任务和产出记录仍保留原始归属。</p></div>{canManage && <Button type="primary" icon={<PlusOutlined />} onClick={() => edit()}>新增成员</Button>}</div><Card title={<><UsergroupAddOutlined /> 小组成员</>}><Table rowKey="id" size="small" dataSource={members} pagination={false} columns={[{ title: '姓名', dataIndex: 'name', width: 150 }, { title: '所属小组', dataIndex: 'team', width: 180 }, { title: '当前身份', dataIndex: 'role', width: 120, render: (v: string) => <Tag color={v === '组长' ? 'gold' : 'blue'}>{v}</Tag> }, { title: '状态', dataIndex: 'status', width: 130, render: (v: string, r: ManagedMember) => <Space><Tag color={v === '在职' ? 'green' : 'default'}>{v}</Tag>{canManageMember(r) && <Switch size="small" checked={v === '在职'} onChange={async () => { await toggleManagedMember(r.id); load(); }} />}</Space> }, { title: '操作', render: (_: unknown, r: ManagedMember) => canManageMember(r) ? <Button type="link" size="small" icon={<EditOutlined />} onClick={() => edit(r)}>编辑</Button> : '-' }]} /></Card><Modal title={editing ? '编辑成员' : '新增成员'} open={open} onCancel={() => setOpen(false)} onOk={submit} okText="保存"><Form form={form} layout="vertical"><Form.Item name="name" label="姓名" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="team" label="所属小组" rules={[{ required: true }]}><Select disabled={actor.role === '组长'} options={ALL_TEAMS.map(team => ({ label: team, value: team }))} /></Form.Item><Form.Item name="role" label="身份" rules={[{ required: true }]}><Select options={[{ label: '组长', value: '组长' }, { label: '组员', value: '组员' }]} /></Form.Item><Form.Item name="status" label="状态" rules={[{ required: true }]}><Select options={[{ label: '在职', value: '在职' }, { label: '已停用', value: '已停用' }]} /></Form.Item></Form></Modal></div>;
}
